<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="E:\Sandpit\NUnitReport\Tests\bin\Debug\Tests.dll" total="4" errors="0" failures="1" not-run="0" inconclusive="1" ignored="0" skipped="0" invalid="0" date="2014-04-18" time="11:25:03">
  <environment nunit-version="2.6.3.13283" clr-version="4.0.30319.18444" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="E:\Sandpit\NUnitReport\Tests\bin\Debug" machine-name="ADRIANHOFMAN-PC" user="Adrian.Hofman" user-domain="AdrianHofman-PC" />
  <culture-info current-culture="en-AU" current-uiculture="en-US" />
  <test-suite type="Assembly" name="E:\Sandpit\NUnitReport\Tests\bin\Debug\Tests.dll" executed="True" result="Failure" success="False" time="0.538" asserts="0">
    <results>
      <test-suite type="Namespace" name="Tests" executed="True" result="Failure" success="False" time="0.509" asserts="0">
        <results>
          <test-suite type="TestFixture" name="AllPassingTestFixture" executed="True" result="Success" success="True" time="0.233" asserts="0">
            <results>
              <test-case name="Tests.AllPassingTestFixture.PassingTest" executed="True" result="Success" success="True" time="0.206" asserts="0">
                <reason>
                  <message><![CDATA[It's all good]]></message>
                </reason>
              </test-case>
            </results>
          </test-suite>
          <test-suite type="TestFixture" name="FailingTestFixture" executed="True" result="Failure" success="False" time="0.263" asserts="0">
            <results>
              <test-case name="Tests.FailingTestFixture.FailingTest" executed="True" result="Failure" success="False" time="0.004" asserts="0">
                <failure>
                  <message><![CDATA[This test fails!]]></message>
                  <stack-trace><![CDATA[at Tests.FailingTestFixture.FailingTest() in e:\Sandpit\NUnitReport\Tests\FailingTestFixture.cs:line 16
]]></stack-trace>
                </failure>
              </test-case>
              <test-case name="Tests.FailingTestFixture.PassingTest" executed="True" result="Success" success="True" time="0.023" asserts="1" />
            </results>
          </test-suite>
          <test-suite type="TestFixture" name="InconclusiveTestFixture" executed="True" result="Inconclusive" success="False" time="0.003" asserts="0">
            <results>
              <test-case name="Tests.InconclusiveTestFixture.InconclusiveTest" executed="True" result="Inconclusive" success="False" time="0.002" asserts="0">
                <reason>
                  <message><![CDATA[No idea whats going on here]]></message>
                </reason>
              </test-case>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>